#!/usr/bin/env/python
"""Tests for analysis.read_editor"""

import pysam
import gzip
import tempfile
import unittest

import analysis.coordinate_mapper as cm
import core_utils.file_utils as fu
from definitions import *

tempfile.tempdir = os.getenv("SCRATCH", "/tmp")

TEST_VCF = """##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=ENST00000398165.7>
##INFO=<ID=AAM_AA_CHANGE,Number=.,Type=String,Description="Can_Cenik_lab.Ian_Hoskins.bioinfo.analysis.coordinate_mapper.AminoAcidMapper comma-delimited amino acid changes.">
##INFO=<ID=VARTYPE,Number=.,Type=String,Description="Variant type. MNPs are confined to a codon. Haplotypes span codons.">
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele frequency in range (0,1).">
##bcftools_normVersion=1.9+htslib-1.9
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
ENST00000398165.7	795	.	GAC	ATG	.	.	AAM_AA_CHANGE=p.D179M;VARTYPE=tri_nt_MNP;AF=0.0001
ENST00000398165.7	804	.	C	G	.	.	AAM_AA_CHANGE=p.R182G;VARTYPE=snp;AF=0.01
ENST00000398165.7	813	.	GG	AT	.	.	AAM_AA_CHANGE=p.G185M;VARTYPE=di_nt_MNP;AF=0.001
"""

TEST_SAM = """@HD	VN:1.0	SO:coordinate
@SQ	SN:ENST00000398165.7	LN:2605
@PG	ID:bowtie2	PN:bowtie2	VN:2.3.4.3	CL:"/opt/anaconda3/envs/CBS_variants/bin/bowtie2-align-s --wrapper basic-0 --maxins 1000 --no-discordant --fr --mp 4 --rdg 6,4 --rfg 6,4 -x /Users/ianhoskins/reference_files/CBS_shortname.fa -1 CBS_test.R1.fq -2 CBS_test.R2.fq"
0000005815	163	ENST00000398165.7	241	42	148M	=	241	-148	ACCATCTGTCCGGTCCCAGCATGCCTTCTGAGACCCCCCAGGCAGAAGTGGGGCCCACAGGCTGCCCCCACCGCTCAGGGCCACACTCGGCGAAGGGGAGCCTGGAGAAGGGGTCCCCAGAGGATAAGGAAGCCAAGGAGCCCCTGTG	SSSSSSSSSSLOKROLRPMKIQQPJRIQJSNLIINKMSJMQNIINKSPQNNLNQNPNPJPRSOPSKPLOPOIPMSSPLOINSJQMMQMKLSNKQLIPIQRNROKPRKMJKIKRLIMSJMRRRPRRRPQNLOIKSJMIRSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:148	YS:i:0	YT:Z:CP
0000005815	83	ENST00000398165.7	241	42	148M	=	241	-148	ACCATCTGTCCGGTCCCAGCATGCCTTCTGAGACCCCCCAGGCAGAAGTGGGGCCCACAGGCTGCCCCCACCGCTCAGGGCCACACTCGGCGAAGGGGAGCCTGGAGAAGGGGTCCCCAGAGGATAAGGAAGCCAAGGAGCCCCTGTG	SSSSSSSSSSINKKNIRJRIJONJRNJIRQISRQIMIJMSLQJMIRRMISPKPQJJMIOQKQOQJKPIMPKJPMSNNSILPILKNRRLIJPQKMMKQIOLPSMIMKLRSILNIMNPISOPPRLRQSNRPMQPJJMRRRSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:148	YS:i:0	YT:Z:CP
0000253933	163	ENST00000398165.7	566	42	150M	=	569	153	GTGTGAGCTCTTGGCCAAGTGTGAGTTCTTCAACGCGGGCGGGAGCGTGAAGGACCGCATCAGCCTGCGGATGATTGAGGATGCTGAGCGCGACGGGACGCTGAAGCCCGGGGACACGATTATCGAGCCGACATCCGGGAACACCGGGAT	SSSSSSSSSSNJMMKKPJQMSSSMINMMKOSQKPKINROPPORPQLKMMIJNSSORRIIPRKRIMIPOMOPMJSNLIQQLORJRJILRJMLPSILQSKMLKKSLJPNMMQIMLKRNQMNSPKPOPQIIINIPMOSRIKROPSLSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000253933	83	ENST00000398165.7	569	42	150M	=	566	-153	TGAGCTCTTGGCCAAGTGTGAGTTCTTCAACGCGGGCGGGAGCGTGAAGGACCGCATCAGCCTGCGGATGATTGAGGATGCTGAGCGCGACGGGACGCTGAAGCCCGGGGACACGATTATCGAGCCGACATCCGGGAACACCGGGATCGG	SSSSSSSQIKKSQINKPSPSLRILIONLIMNKJNQPRINPOJOKONRPSKSQININOKOPONIPINNOIRSPOPJSSQPMPPLOOSKNOSJRINIKJNOMRLSSKJLLJLONQOJSMNPMJLMIMMPLSIIMMLLLONMSSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000224875	163	ENST00000398165.7	680	42	150M	=	683	153	CACGATTATCGAGCCGACATCCGGGAACACCGGGATCGGGCTGGCCCTGGCTGCGGCAGTGAGGGGCTATCGCTGCATCATCGTGATGCCAGAGAAGATGAGCTCCGAGAAGGTGGACGTGCTGCGGGCACTGGGGGCTGAGATTGTGAG	SSSSSSSSSSOKROSNOMKISLLKKLNPLIJQOSJJMRLQIJJQRSRNMKLLOLJSJRNJRSPPPLMRQKQMIRQRLJOPSOJMKLRRMJIJOOJQLSPLKKMJSNNQLOMJSOJKRRMPPLOOIQPNRQJSLJSOKOKMMMMSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000224875	83	ENST00000398165.7	683	42	150M	=	680	-153	GATTATCGAGCCGACATCCGGGAACACCGGGATCGGGCTGGCCCTGGCTGCGGCAGTGAGGGGCTATCGCTGCATCATCGTGATGCCAGAGAAGATGAGCTCCGAGAAGGTGGACGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGAC	SSSSSSSNSRKQNMLQIKNLNJPKLIINNNQRNIROIQJMJLLKOQSQIIKSOMOOQQIRRRNNMLIOLKSJQQJKKLQRSIQPLJLRMLPKOPMNPLIRLLIJNQLKISPOSKKIMIIKSMKMJKSKKORKISNPROOKSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000001369	163	ENST00000398165.7	794	42	150M	=	797	153	GGACGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGACGCCCACCAATGCCAGGTTCGACTCCCCGGAGTCACACGTGGGGGTGGCCTGGCGGCTGAAGAACGAAATCCCCAATTCTCACATCCTAGACCAGTACCGCAACGCCAGCAA	SSSSSSSSSSMOINJNKNNLLRNLPRRNNKLLNMRNNLJPMLSOINMSILMLMRLSLPNKLLRNJMSKJJIPQMJNRLQOJQLOSRORNQSQRPOPOSIPMPILKNNLPMNIQJPOQPILOOMORLPILSONMKLRLPPRIQPSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000051899	163	ENST00000398165.7	794	42	150M	=	797	153	GGACGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGACGCCCACCAATGCCAGGTTCGACTCCCCGGAGTCACACGTGGGGGTGGCCTGGCGGCTGAAGAACGAAATCCCCAATTCTCACATCCTAGACCAGTACCGCAACGCCAGCAA	SSSSSSSSSSKPLJJQLOKSLOMIPSIPMILSORJONIQLPKJSMJRKNIIJRPSSIOJSOOMSKQKOQMNLIOQRSQIPILKSRQPMNIRMSNKQOOJQSLMQRNJJPJOJLKRSOKSQIPSKKQPSPSLJJKSPRMNJNJLSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000225689	99	ENST00000398165.7	794	42	150M	=	797	153	GGACGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGACGCCCACCAATGCCAGGTTCGACTCCCCGGAGTCACACGTGGGGGTGGCCTGGCGGCTGAAGAACGAAATCCCCAATTCTCACATCCTAGACCAGTACCGCAACGCCAGCAA	SSSSSSSSSSPNIIJKQLRPOSSJKSMKOQKPIQKONRJNQRRPJNOQLOMPSPMSSNQRJIRPOOJIPLNSKNLMKPNSRLJLRMMJKIRPJIRKSJKMLSQOQQSJLPMSIPRLLQMIIROKOPNROSOPSKJJSPPSQIQSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000001369	83	ENST00000398165.7	797	42	150M	=	794	-153	CGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGACGCCCACCAATGCCAGGTTCGACTCCCCGGAGTCACACGTGGGGGTGGCCTGGCGGCTGAAGAACGAAATCCCCAATTCTCACATCCTAGACCAGTACCGCAACGCCAGCAACCC	SSSSSSSIRMRPPMKORMQQKPOQRJLQPLOKSQJOIMJJILKPKJQKNRIJJLJPRMNIRKJMJKKOJQPSKSSNJIILLLSRMPPNLIJOOJNNMMLPIOKLPSMQSQOQKPOSSQKISLQSLLRRKNSMRORRNJKOSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000051899	83	ENST00000398165.7	797	42	150M	=	794	-153	CGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGACGCCCACCAATGCCAGGTTCGACTCCCCGGAGTCACACGTGGGGGTGGCCTGGCGGCTGAAGAACGAAATCCCCAATTCTCACATCCTAGACCAGTACCGCAACGCCAGCAACCC	SSSSSSSNMRMMNRNPRQKRNRIOMSLPIIISLOQIOKKOOOMLOLQINPNMNNQOIMNJOQRSMPQISIIQINSJORMRROLSJQMLISKMLPMJMMSQINOOQOOSQMJMIJJLRSKPNSSSOMQPNSNKQJLIJJKKSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000225689	147	ENST00000398165.7	797	42	150M	=	794	-153	CGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGACGCCCACCAATGCCAGGTTCGACTCCCCGGAGTCACACGTGGGGGTGGCCTGGCGGCTGAAGAACGAAATCCCCAATTCTCACATCCTAGACCAGTACCGCAACGCCAGCAACCC	SSSSSSSNKMQOSOKSKJRQJJPKLKPRPOISPKNLQSSKLMLIKKPOSOQONSMILKSQISIJJMQOMNKQPQMQRIQRQQQSSJISSMSSQJILPIPMLOLQNMIMIRLQJSNKLKQJOSPRNMSPJKQJIQMKSIPSSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000003129	163	ENST00000398165.7	908	42	147M	=	908	-147	TTCTCACATCCTAGACCAGTACCGCAACGCCAGCAACCCCCTGGCTCACTACGACACCACCGCTGATGAGATCCTGCAGCAGTGTGATGGGAAGCTGGACATGCTGGTGGCTTCAGTGGGCACGGGCGGCACCATCACGGGCATTGC	SSSSSSSSSSOLPSKLNQOJLLNMPKLJJJNKQKOMMOKQPNLNOOLMJOMSQKIIQLKNLIPRQKNQIQRQIMJQSIQONKSIMONLJQSLMQOLNJSONKMNNLNNPKLQKPPIOMPQQQKOKPMSRPRKONMNNSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:147	YS:i:0	YT:Z:CP
0000003129	83	ENST00000398165.7	908	42	147M	=	908	-147	TTCTCACATCCTAGACCAGTACCGCAACGCCAGCAACCCCCTGGCTCACTACGACACCACCGCTGATGAGATCCTGCAGCAGTGTGATGGGAAGCTGGACATGCTGGTGGCTTCAGTGGGCACGGGCGGCACCATCACGGGCATTGC	SSSSSSSSSSIJJMPQKJKKINNNMKNPOQPJJNMLIRNKIRQPJNRPRSOQQMIMOIKNPLILONPKONSOOQJRSIQMIPNQSQSSNSKSOONKJJSQRIPOJQONPOQJRJSKRNMRQKRLNSQILNSQKOOIRSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:147	YS:i:0	YT:Z:CP
0000323491	99	ENST00000398165.7	1016	42	150M	=	1019	153	GGCTTCAGTGGGCACGGGCGGCACCATCACGGGCATTGCCAGGAAGCTGAAGGAGAAGTGTCCTGGATGCAGGATCATTGGGGTGGATCCCGAAGGGTCCATCCTCGCAGAGCCGGAGGAGCTGAACCAGACGGAGCAGACAACCTACGA	SSSSSSSSSSNIILOQONPRQOPJOIOLNJJIOPNKQNPOKQRRSRJMPKSSPQQNJOMIJMKNIQRQPRSRIMNQNPONMRPKROKNORRRQQIISIQRONILSJKKRPSSIPKILKIMKQPNNOLJNKRIORKIMPMIPIKSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000323491	147	ENST00000398165.7	1019	42	150M	=	1016	-153	TTCAGTGGGCACGGGCGGCACCATCACGGGCATTGCCAGGAAGCTGAAGGAGAAGTGTCCTGGATGCAGGATCATTGGGGTGGATCCCGAAGGGTCCATCCTCGCAGAGCCGGAGGAGCTGAACCAGACGGAGCAGACAACCTACGAGGT	SSSSSSSIRJLKSRNOKILLMKJMQKINJQPNSJIQNIJMLJMRPPRQIRRIOQLRKKNQMPISMOJNJOOKKPJOSMNMSKSOONJNKQRSLQPOSMLQMRLRRSOIPLKIJMNKLMJJMKQQKPPOKJLNLSJNLKSMSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000214705	163	ENST00000398165.7	1358	42	150M	=	1361	153	GGGCCAGCGCTGCGTGGTCATTCTGCCCGACTCAGTGCGGAACTACATGACCAAGTTCCTGAGCGACAGGTGGATGCTGCAGAAGGGCTTTCTGAAGGAGGAGGACCTCACGGAGAAGAAGCCCTGGTGGTGGCACCTCCGTGTTCAGGA	SSSSSSSSSSILOKJNNLJKRORJMSOLMLQMNRSOQQIPKJRKOQKMKMRNKIMNIIRIJPNQIIPNKQRNQMIMRRJLPSIMJRNNNNPKNPPIJJSKRRRKRNOSLQQOOSPNKMOSJLNOSONNJRQONORIRPMSOMLSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000214705	83	ENST00000398165.7	1361	42	150M	=	1358	-153	CCAGCGCTGCGTGGTCATTCTGCCCGACTCAGTGCGGAACTACATGACCAAGTTCCTGAGCGACAGGTGGATGCTGCAGAAGGGCTTTCTGAAGGAGGAGGACCTCACGGAGAAGAAGCCCTGGTGGTGGCACCTCCGTGTTCAGGAGCT	SSSSSSSKKMRPKISSNKMISKISRQPOJKJJQLNRKRIQPMJLPMPJLRKJIJQSKJJPSIQLQLRMQONOMLKNSQLKKOOSPLNJRIJSIIIQQRQLRJJPKRNSOKPRJNMSLSKSLMRLRLPQIQIIPIPKSOIKSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP
0000099776	99	ENST00000398165.7	1805	42	132M	=	1805	-132	GATCCAGTACCACAGCACCGGGAAGTCCAGTCAGCGGCAGATGGTGTTCGGGGTGGTCACCGCCATTGACTTGCTGAACTTCGTGGCCGCCCAGGAGCGGGACCAGAAGTGAAGTCCGGAGCGCTGGGCGGT	SSSSSSSSSSONQJOQQSQKNJSKRMNQKJLLOSJQJKLMQPLKKLSLRQLPPIPSLJSSJJMMOJINMRJJLSJMQLMPNNPSJQNNILPJKJNLNKPNLRJRSROMQRKKSRPRKIPLIQSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:132	YS:i:0	YT:Z:CP
0000099776	147	ENST00000398165.7	1805	42	132M	=	1805	-132	GATCCAGTACCACAGCACCGGGAAGTCCAGTCAGCGGCAGATGGTGTTCGGGGTGGTCACCGCCATTGACTTGCTGAACTTCGTGGCCGCCCAGGAGCGGGACCAGAAGTGAAGTCCGGAGCGCTGGGCGGT	SSSSSSSSSSINNIKMSNPPOONNOMMQIQOMRRSNKPLKLILMPKPPNMQNSLPRMRILNMIMIJNSLNJMOOQOPKRJNILIQPKQRNMOSNOQNJRKNONPSJLRRQIIMKOQKPOJMKSSSSSSSSSS	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:132	YS:i:0	YT:Z:CP
"""


class TestReadEditor(unittest.TestCase):
    """Tests for ReadEditor."""

    GFF = "CBS_pEZY3.gff"
    GFF_REF = "CBS_pEZY3.fa"
    PRIMERS = "CBS_pEZY3_primers.bed"
    TARGETS = "CBS_pEZY3_targets.bed"
    APPRIS_REF = "GRCh38.chr21.fa.gz"
    CBS_REF = "CBS.fa"
    PKNOX1_REF = "PKNOX1.fa"

    @classmethod
    def setUpClass(cls):
        """Set up for TestReadEditor."""

        cls.tempdir = tempfile.mkdtemp()
        cls.test_dir = os.path.dirname(__file__)
        cls.test_data_dir = os.path.abspath(os.path.join(cls.test_dir, "..", "test_data"))

        # Validate coordinate mapping for both a custom vector reference and for default APPRIS annotations

        # Custom reference
        cls.cbs_pezy3_ref = os.path.join(cls.test_data_dir, cls.GFF_REF)
        cls.cbs_pezy3_gff = os.path.join(cls.test_data_dir, cls.GFF)

        cls.cbs_pezy3_aa_mapper = cm.AminoAcidMapper(
            gff=cls.cbs_pezy3_gff, ref=cls.cbs_pezy3_ref, outdir=cls.tempdir, use_pickle=False, make_pickle=False,
            overwrite_pickle=False, mut_sig=cm.AminoAcidMapper.MUT_SIG_ANY, filter_unexpected=False)

        cls.cbs_pezy3_trx_seq = ""
        with open(cls.cbs_pezy3_ref, "r") as ref_fa:
            for i, line in enumerate(ref_fa):
                if i == 0:
                    continue
                cls.cbs_pezy3_trx_seq += line.rstrip(fu.FILE_NEWLINE)

        cls.cbs_pezy3_cds_seq = cls.cbs_pezy3_trx_seq[973:2629]

        # APPRIS references on both strands
        cls.appris_ref_gz = os.path.join(cls.test_data_dir, cls.APPRIS_REF)

        # This just has CBS and PKNOX1 annotations
        cls.appris_gff = os.path.join(cls.test_data_dir, GENCODE_TRX_GFF)

        # For sequence comparison use the sequences extracted from the transcriptome
        cls.cbs_ref = os.path.join(cls.test_data_dir, cls.CBS_REF)
        cls.pknox1_ref = os.path.join(cls.test_data_dir, cls.PKNOX1_REF)

        with gzip.open(cls.appris_ref_gz) as appris_ref_in, \
                tempfile.NamedTemporaryFile(suffix=".fa", delete=False) as appris_ref_out:

            for line in appris_ref_in:
                appris_ref_out.write(line)

            cls.temp_ref_fa = appris_ref_out.name

        pysam.faidx(cls.temp_ref_fa)

        cls.appris_aa_mapper = cm.AminoAcidMapper(
            gff=cls.appris_gff, ref=cls.temp_ref_fa, outdir=cls.tempdir, use_pickle=False, make_pickle=False,
            overwrite_pickle=False, mut_sig="NNK", filter_unexpected=False)

        cls.appris_cbs_trx_seq = ""
        with open(cls.cbs_ref, "r") as ref_fa:
            for i, line in enumerate(ref_fa):
                if i == 0:
                    continue
                cls.appris_cbs_trx_seq += line.rstrip(fu.FILE_NEWLINE)

        cls.appris_cbs_cds_seq = cls.appris_cbs_trx_seq[260:1913]

        cls.appris_pknox1_trx_seq = ""
        with open(cls.pknox1_ref, "r") as ref_fa:
            for i, line in enumerate(ref_fa):
                if i == 0:
                    continue
                cls.appris_pknox1_trx_seq += line.rstrip(fu.FILE_NEWLINE)

        cls.appris_pknox1_cds_seq = cls.appris_pknox1_trx_seq[211:1519]

    @classmethod
    def tearDownClass(cls):
        """Tear down for TestReadEditor."""

        fu.safe_remove((cls.tempdir, cls.temp_ref_fa), force_remove=True)